### ISSUE TITLE
Does not work in textareas in TiddlyWiki

### ISSUE THREAD

**Issue by MaxGyver83** [jlebon/textern#56] opened 2020-02-10 18:00 UTC
`textern` does not work in TiddlyWiki textareas. How to reproduce:

1. Go to https://tiddlywiki.com
2. Click on the `+` button (_Create a new tiddler_) on the right side panel. This opens a new `div` with 5 `input`s and a large `textarea`.
3. Click into the textarea.
4. Use your textern shortcut.
5. Nothing happens.

**Comment by MaxGyver83** [comment] 2020-02-11 20:35
I have tried to find the reason for this issue.

When I enter text into one of the inputs, I get values like those in `shortcut.js`:
* `e` = `[object KeyboardEvent]`
* `window.event` = `undefined`
* `keyCode` = `73`
* `character` = `i`

When I enter text into the textarea, I get:
* `e` = `[object Event]`
* `window.event` = `[object KeyboardEvent]`
* `keyCode` = `73`
* `character` = `i`

`keyCode` doesn't get updated in the textarea, no matter which key I press.

Then I changed

```javascript
e = e || window.event;
```
to

```javascript
e = window.event || e;
```

Then `e` is always a `KeyboardEvent` and the keyCodes are correct. But I still don't get vim openend.

**Comment by jlebon** [comment] 2020-04-04 14:49
Right yeah, I think the root cause for this is similar to what I'm hitting in https://github.com/jlebon/textern/pull/43. I.e. newly dynamically created textareas throw off `shortcut.js`.

**Comment by MaxGyver83** [comment] 2020-04-05 12:08
OK, thanks for your answer!

**Comment by jlebon** [comment] 2020-04-05 21:47
This is fixed in the v0.6 release!

**Closed by jlebon** 2020-04-05 21:47 UTC

**Comment by MaxGyver83** [comment] 2020-04-06 16:02
Awesome! Thank you.
